class Knowledge_base():
    def __init__(self):
        self.knowledge_base_dict = {
            "NIDC_knowledge_base" : [
            "Well-defined borders: The tumor is clearly separated from the surrounding normal breast tissue.",
            "Solid growth pattern: The tumor cells are arranged in solid nests or masses.",
            "Lack of invasion: The tumor cells have not breached the basement membrane of the ducts.",
            "Uniform nuclear size and shape: The tumor cells have relatively uniform nuclei with visible nucleoli.",
            "Minimal mitotic activity: There are few or no mitotic figures observed within the tumor.",
            "Stroma: The stroma surrounding the tumor is relatively dense and fibrotic.",
            "Ductal structures: Intact ducts are seen in the surrounding normal breast tissue.",
            "Lobular architecture: The tissue is organized into lobules, which are clusters of acini surrounded by stroma.",
            "Dilated ducts: The ducts within the lobules are dilated and contain intraluminal secretions.",
            "Hyperplasia: There is evidence of hyperplasia (increased cell proliferation) within the ductal epithelium.",
            "Lack of atypia: The cells appear relatively normal in size, shape, and arrangement.",
            "Minimal mitotic activity: There are few or no mitotic figures observed.",
            ###augmented
            "Well-Defined Borders: Clear separation from surrounding normal tissue.",
            "Solid Growth Pattern: Tumor cells arranged in solid nests or masses.",
            "Lack of Invasion: Tumor cells confined within ductal structures.",
            "Uniform Nuclear Features: Uniform nuclear size and shape with visible nucleoli.",
            "Minimal Mitotic Activity: Few or no dividing cells.",
            "Dense Fibrotic Stroma: Dense connective tissue surrounding the tumor.",
            "Intact Ductal Structures: Preserved ducts in normal breast tissue.",
            "Preserved Lobular Architecture: Normal lobular organization.",
            "Ductal Dilation: Dilated ducts with intraluminal secretions.",
            "Epithelial Hyperplasia: Increased cell proliferation within ducts.",
            "Lack of Cellular Atypia: Normal cell size, shape, and arrangement.",
            "Minimal Mitotic Activity: Few or no dividing cells."
            ###augmented short phrase
            "Well-Defined Borders.",
            "Clear Separation from Surrounding Tissue.",
            "Solid Growth Pattern.",
            "Tumor Cells in Solid Nests or Masses.",
            "Lack of Invasion.",
            "Tumor Cells Confined Within Ducts.",
            "Uniform Nuclear Features.",
            "Uniform Nuclear Size and Shape.",
            "Visible Nucleoli.",
            "Minimal Mitotic Activity.",
            "Few or No Dividing Cells.",
            "Dense Fibrotic Stroma.",
            "Dense Connective Tissue.",
            "Intact Ductal Structures.",
            "Preserved Ducts.",
            "Preserved Lobular Architecture.",
            "Normal Lobular Organization.",
            "Ductal Dilation.",
            "Dilated Ducts with Secretions.",
            "Epithelial Hyperplasia.",
            "Increased Cell Proliferation.",
            "Lack of Cellular Atypia.",
            "Normal Cell Size, Shape, and Arrangement.",
            "Minimal Mitotic Activity.",
            "Few or No Dividing Cells."
            ],
            "IDC_knowledge_base" : [
                "Loss of lobular architecture: In contrast to normal breast tissue, which is organized into lobules, invasive ductal carcinoma often disrupts this structure.",
                "Loss of lobular architecture: The normal lobular structure of breast tissue is disrupted, with irregular nests of tumor cells infiltrating the surrounding stroma.",
                "Invasive growth: The tumor cells have breached the basement membrane of the ducts and are invading the surrounding stroma.",
                "Invasive growth: The tumor cells have breached the basement membrane of the ducts and are invading the surrounding tissue.",
                "Invasive growth: The tumor cells have breached the basement membrane and are infiltrating the surrounding stroma.",
                "Cellular atypia: The tumor cells exhibit abnormal features such as enlarged nuclei, prominent nucleoli, and increased mitotic activity.",
                "Necrosis: Areas of cell death (necrosis) present within the tumor.",
                "Necrosis: Areas of cell death (necrosis) are visible within the tumor.",
                "Desmoplastic reaction: The stroma surrounding the tumor show increased fibrosis (desmoplastic reaction).",
                "Desmoplastic reaction: The stroma surrounding the tumor shows increased fibrosis.",
                "Cellular arrangement: The tissue appears to be organized in a disorganized, infiltrative pattern.",
                "Mitotic activity: There appears to be an increased number of mitotic figures (cells undergoing division), which is a potential indicator of malignancy.",
                "Stroma: The stroma (connective tissue) surrounding the tumor cells may be desmoplastic, characterized by increased collagen deposition.",
                ###augmented
                "Disrupted Lobular Architecture: Loss of normal lobular organization.",
                "Invasive Growth: Tumor cells breach basement membrane and infiltrate stroma.",
                "Cellular Atypia: Abnormal cells with enlarged nuclei, prominent nucleoli, and increased mitotic activity.",
                "Tissue Necrosis: Areas of cell death within the tumor.",
                "Desmoplastic Reaction: Increased fibrosis in surrounding stroma.",
                "Disorganized Cellular Arrangement: Infiltrative growth pattern.",
                "Increased Mitotic Activity: High number of dividing cells.",
                "Desmoplastic Stroma: Increased collagen deposition in surrounding stroma."
                ###augmented short phrase
                "Disrupted Lobular Architecture.",
                "Loss of Normal Lobular Organization.",
                "Invasive Growth.",
                "Tumor Cells Breach Basement Membrane.",
                "Infiltration of Stroma.",
                "Cellular Atypia.",
                "Abnormal Cells.",
                "Enlarged Nuclei.",
                "Prominent Nucleoli.",
                "Increased Mitotic Activity.",
                "Tissue Necrosis.",
                "Areas of Cell Death.",
                "Desmoplastic Reaction.",
                "Increased Fibrosis in Stroma.",
                "Disorganized Cellular Arrangement.",
                "Infiltrative Growth Pattern.",
                "Increased Mitotic Activity.",
                "High Number of Dividing Cells.",
                "Desmoplastic Stroma.",
                "Increased Collagen Deposition."
            ],
            "benign_gpt_knowledge_base" : [
                "Well-defined tumor borders without invasion.",
                "Uniform cell size and shape.",
                "Low nuclear-to-cytoplasmic ratio.",
                "Preserved normal tissue structure.",
                "Few or no mitotic figures.",
                "Encapsulated by smooth fibrous stroma.",
                "No necrosis or hemorrhage.",
                "Regular, round to oval nuclei.",
                "No vascular or lymphatic invasion.",
                "Homogeneous, single-type cell population."
                "Well-circumscribed tumor borders, clearly defined and separated from adjacent normal tissue with no invasion.",
                "Uniform cell morphology with consistent shape and size, minimal variation in nuclear and cytoplasmic features.",
                "Low nuclear-to-cytoplasmic ratio, with nuclei relatively small compared to cytoplasm indicating differentiated non-malignant cells.",
                "Preserved tissue architecture resembling normal histology, such as glands in colon, ducts in breast, or alveoli in lung.",
                "Absent or minimal mitotic figures, indicating very low cell division activity with rare normal mitoses.",
                "Smooth, fibrous stroma surrounding the lesion, with an encapsulated or organized fibrous capsule and no desmoplastic reaction.",
                "Lack of necrosis or hemorrhage within the tumor.",
                "Regular, round to oval nuclei with smooth contours, uniform chromatin distribution, and inconspicuous nucleoli.",
                "No evidence of vascular or lymphatic invasion, with intact blood vessels and lymphatics around the lesion.",
                "Monomorphic cell populations appearing homogeneous and of a single cell type, consistent with benign proliferation."
            ],
            "malignant_gpt_knowledge_base" : [
                "Frequent mitoses show high cell division.",
                "Abnormal mitotic figures like multipolar spindles appear.",
                "Apoptotic bodies indicate cell death near mitoses.",
                "Tumor edges are irregular and invade nearby tissue.",
                "No capsule separates tumor from normal tissue.",
                "Reactive fibrous tissue surrounds tumor clusters.",
                "Tumor invades vessels, lymphatics, or nerves.",
                "Cells vary greatly in size and shape (pleomorphism).",
                "Some cells are large, irregular, or multinucleated.",
                "Pleomorphism reflects tumor genetic instability.",
                "Nuclei are dark and irregularly shaped.",
                "Nucleoli are large and often multiple.",
                "New blood vessels are irregular and thin-walled.",
                "Tumor vessels are leaky and contain red blood cells."
                "Frequent mitotic figures indicate high proliferative activity.",
                "Atypical mitoses such as multipolar spindles are often observed.",
                "Apoptotic bodies (condensed, dying cells) are often present near mitotic figures.",
                "Tumor margins are ill-defined and infiltrate into surrounding stroma.",
                "No fibrous capsule separates tumor from adjacent normal tissue.",
                "Peritumoral desmoplasia (reactive fibrous stroma) commonly surrounds tumor nests.",
                "Tumor may invade nearby vessels, lymphatics, or nerves.",
                "Tumor cells show marked variability in size and shape (pleomorphism).",
                "Some tumor cells appear enlarged, irregular, or multinucleated.",
                "Pleomorphism reflects genomic instability and tumor heterogeneity.",
                "Atypical nuclear features include hyperchromasia and irregular contours.",
                "Nucleoli are prominent and sometimes multiple, reflecting high activity.",
                "Newly formed capillaries are irregular, dilated, and thin-walled.",
                "Tumor vasculature is often leaky and surrounded by red blood cells."
            ],
        "benign_breasKHis": [
            "benign",
            "benign tissues",
            "Well-defined borders: The lesions have clear and distinct margins, separating them from the surrounding normal tissue.",
            "Well-defined borders: The lesions are clearly demarcated from the surrounding normal breast tissue.",
            "Epithelial proliferation: There is an increase in the number of epithelial cells lining the ducts and lobules.",
            "Stromal changes: The supporting connective tissue (stroma) may show varying degrees of proliferation and changes in cellularity.",
            "Absence of nuclear atypia: The nuclei of the epithelial cells maintain a normal appearance, without significant variation in size, shape, or chromatin pattern.",
            "No evidence of mitotic activity: There are no abnormal cell divisions (mitoses) observed within the lesion.",
            "Epithelial hyperplasia: An increase in the number of epithelial cells, often with crowding and overlapping.",
            "Ductal or lobular enlargement: The ducts or lobules may be enlarged, but without significant distortion or invasion of surrounding tissue.",
            "Stromal fibrosis: Increased fibrous tissue within the lesion, often with a dense, collagenous appearance.",
            "Eosinophilic changes: A pink, glassy appearance of the stroma due to increased eosinophilic staining.",
            "Absence of necrosis: No areas of tissue death or decay within the lesion.",
            ###remove starting summarizations
            "Lesions have clear and distinct margins.",
            "Lesions are clearly demarcated.",
            "Increase in epithelial cells.",
            "Changes in connective tissue.",
            "Normal nuclear appearance.",
            "No abnormal cell divisions.",
            "Increased number of epithelial cells.",
            "Enlarged ducts or lobules.",
            "Increased fibrous tissue.",
            "Pink, glassy appearance of the stroma.",
            "No tissue death.",
            ##aug
            "Increased epithelial cells.",
            "Normal cell nuclei.",
            "No abnormal cell division.",
            "Increased cell growth in the breast tissue.",
            "No abnormal cell changes.",
            ###from dictionary
            "Benign tumours tend to have very few dividing cells.",
            "Most benign tumours are separated from the surrounding normal tissue.",
            "non-cancerous cells",
            ##from provided image
            # "Lesions are clearly demarcated from the surrounding normal tissue.",
            # "The nuclei of the cells are relatively uniform in size and shape, with minimal variation.",
            # "The normal tissue architecture, such as glandular structures or stromal arrangement, is generally maintained, although it may be distorted or compressed.",
            # "There are few or no mitotic figures observed, indicating a slow growth rate."
            ],
       
        "malignant_breaKHis":[
            "malignant",
            "malignant tissues",
            "Nuclear pleomorphism: Variation in size, shape, and color intensity of nuclei.",
            "Increased nuclear-to-cytoplasmic ratio: Nuclei appear larger relative to the surrounding cytoplasm.",
            "Mitotic figures: Presence of dividing cells, indicating rapid cell proliferation.",
            "Loss of cell polarity: Disorganized arrangement of cells within the tissue.",
            "Loss of normal tissue architecture: Disruption of the typical glandular or ductal structures.",
            "Increased cellularity: Higher density of cells within the tissue.",
            "Nuclear hyperchromasia: Increased staining intensity of nuclei.",
            "Necrosis: Areas of dead tissue within the tumor.",
            "Lymphocytic infiltration: Increased number of lymphocytes surrounding or within the tumor.",
            "Abnormal mitotic figures: Mitotic figures with atypical appearance, such as abnormal spindle formation or multipolar mitoses.",
            "Giant cells: Large, multinucleated cells within the tumor.",
            "Comedo necrosis: A specific type of necrosis characterized by central necrosis surrounded by a ring of tumor cells.",
            "Tumor giant cells: Large, multinucleated tumor cells.",
            "Nuclear molding: Nuclei that appear compressed or distorted due to crowding.",
            "Nuclear pleomorphism: Nuclei vary in size, shape, and color.",
            "Increased nuclear-to-cytoplasmic ratio: Nuclei are larger relative to the cytoplasm.",
            "Mitotic figures: Cells are actively dividing.",
            "Loss of cell polarity: Cells are disorganized.",
            "Loss of normal tissue architecture: Tissue structure is disrupted.",
            "Increased cellularity: Tissue has a higher cell density.",
            "Nuclear hyperchromasia: Nuclei are darkly stained.",
            "Necrosis: Tissue death is present.",
            "Lymphocytic infiltration: Immune cells are present around or within the tumor.",
            "Abnormal mitotic figures: Cell division is abnormal.",
            ###remove starting summarizations
            "Nuclei are larger relative to the cytoplasm.",
            "Immune cells are present around or within the tumor.",
            ##aug
            "Large, multi-nucleated cells are present.",
            "Central necrosis is surrounded by tumor cells.",
            "Large, multi-nucleated tumor cells are present.",
            "Nuclei vary in size, shape, and color.",
            "Nuclei are large relative to cytoplasm.",
            "Cells are actively dividing.",
            "Cells are disorganized.",
            "Tissue structure is disrupted.",
            "Tissue has a higher cell density.",
            "Nuclei are darkly stained.",
            "Tissue death is present.",
            "Immune cells are present.",
            "Cell division is abnormal.",
            "Large, multinucleated cells are present.",
            "Central necrosis surrounded by tumor cells.",
            "Large, multinucleated tumor cells are present.",
            "Nuclei are compressed or distorted.",
            ###from dictionary
            "malignant (cancerous) tumours tend to invade (spread) into the surrounding healthy tissue.",
            "cancerous growth of cells.",
            "malignant neoplasm.",
            "cancerous tumour",
            "Grow uncontrollably.",
            "Damage surrounding normal tissue.",
            "tumour invasion into the surrounding normal tissue.",
            ]
        }




